Tags resources as "Deleted" instead of deleting
chanzuckerberg/chamber pull request #1
Opened 2018-06-18 16:27 UTC by tfrcarvalho

TODO: update store test to include ListTagsForResource mock.

- `delete` command tags resources as delete instead of deleting (Goal: preventing accidental total loss of credentials to resources).
- Added force flag to actually delete the resource (previous default behavior)
- Updated `list`, `exec` and `read` commands to support new delete behavior.

2018-06-19 17:01 UTC, ryanking approved these changes

2018-06-20 21:02 UTC, tzjames requested changes
Thanks Tiago!  Looks great.  Just a couple of small inline nits, plus I think you might not be handling an edge case.  If someone deletes a secret, but then tries and add it back in, ideally I think it should just remove the deleted tag and set the new value.

2018-06-20 21:02 UTC, tzjames commented on README.md
>  This repo is a fork of original Chamber tool ([segmentio/chamber](https://github.com/segmentio/chamber)). THer goal is to add the following functionality:
typo: THer -> The

2018-06-20 21:02 UTC, tzjames commented on cmd/delete.go
> +		Short: "Tag a secreted as deleted (it will not be Delete a secret, including all versions",
This is a bit hard to read.  Am I getting at what you are trying to say with:
"Tag a secret as deleted. (Old versions of the secret will remain in the parameter store)

2018-06-20 21:15 UTC, tfrcarvalho commented
Yeah, I was going to add a "recover" command to explicitly recover the secret. I guess i can clear the tag when a new version is written.

2018-06-21 18:54 UTC, tzjames approved these changes
Updates look good!  Looking forward to start using this.

2018-06-21 18:54 UTC, tzjames commented on store/ssmstore.go
I suppose this is mostly self explanatory, but you could add a comment.
// We remove any "deleted" tag in case the item was previously deleted.

2018-06-22 17:12 UTC, merged